"""
pdf_gen.py — Generate a styled PDF from a research report using reportlab.
"""
import io, re
from datetime import datetime

def generate_pdf(query: str, report: str, stats: dict = None) -> bytes:
    """Returns PDF as bytes."""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib.colors import HexColor
        from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer,
                                        HRFlowable, Table, TableStyle)
        from reportlab.lib.enums import TA_LEFT, TA_CENTER
    except ImportError:
        return _plain_text_fallback(query, report)

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
        leftMargin=2.5*cm, rightMargin=2.5*cm,
        topMargin=2.5*cm, bottomMargin=2.5*cm)

    # Colors
    BG      = HexColor("#0c0c0e")
    ACCENT  = HexColor("#7c6af7")
    WHITE   = HexColor("#e8eaf0")
    MUTED   = HexColor("#6b7280")
    LIGHT   = HexColor("#c4c7d9")

    styles = getSampleStyleSheet()
    # Custom styles
    title_style = ParagraphStyle("Title2",
        fontName="Helvetica-Bold", fontSize=22, leading=28,
        textColor=ACCENT, spaceAfter=6, alignment=TA_LEFT)
    meta_style = ParagraphStyle("Meta",
        fontName="Helvetica", fontSize=8, leading=12,
        textColor=MUTED, spaceAfter=16)
    h2_style = ParagraphStyle("H2",
        fontName="Helvetica-Bold", fontSize=13, leading=18,
        textColor=LIGHT, spaceBefore=20, spaceAfter=6)
    body_style = ParagraphStyle("Body2",
        fontName="Helvetica", fontSize=10, leading=16,
        textColor=MUTED, spaceAfter=8, alignment=TA_LEFT)
    link_style = ParagraphStyle("Link",
        fontName="Helvetica", fontSize=9, leading=14,
        textColor=ACCENT, spaceAfter=4)

    story = []

    # Header
    story.append(Paragraph(query, title_style))
    ts = datetime.now().strftime("%B %d, %Y · %H:%M")
    meta_txt = f"Generated by Synapse Research Terminal · {ts}"
    if stats:
        meta_txt += f" · {stats.get('elapsed','?')}s · {stats.get('sources','?')} sources"
    story.append(Paragraph(meta_txt, meta_style))
    story.append(HRFlowable(width="100%", thickness=0.5, color=ACCENT, spaceAfter=16))

    # Parse and render report sections
    lines = report.split("\n")
    for line in lines:
        line = line.strip()
        if not line:
            story.append(Spacer(1, 4))
            continue
        if line.startswith("## "):
            heading = line[3:].strip()
            story.append(Paragraph(heading, h2_style))
            story.append(HRFlowable(width="100%", thickness=0.3, color=HexColor("#1e1e28"), spaceAfter=4))
        elif line.startswith("---"):
            story.append(HRFlowable(width="100%", thickness=0.3, color=HexColor("#1e1e28"), spaceBefore=8, spaceAfter=8))
        elif line.startswith("**[") and "](" in line:
            # Source line — extract and render nicely
            clean = re.sub(r'\*\*|\[|\]|\(|\)', '', line)
            clean = re.sub(r'https?://\S+', '', clean).strip()
            story.append(Paragraph(f"• {clean}", link_style))
        else:
            # Clean markdown formatting
            text = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', line)
            text = re.sub(r'\*(.*?)\*', r'<i>\1</i>', text)
            text = re.sub(r'\[([^\]]+)\]\([^\)]+\)', r'\1', text)
            text = re.sub(r'\[(\d+)\]', r'[\1]', text)
            story.append(Paragraph(text, body_style))

    # Footer
    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", thickness=0.5, color=HexColor("#1e1e28")))
    story.append(Spacer(1, 6))
    story.append(Paragraph("Generated by Synapse · Powered by Llama 3.3 70B + RAG", meta_style))

    doc.build(story)
    return buf.getvalue()


def _plain_text_fallback(query: str, report: str) -> bytes:
    """If reportlab not installed, return plain text bytes."""
    text = f"RESEARCH REPORT\n{'='*50}\n{query}\n{'='*50}\n\n{report}"
    return text.encode("utf-8")